# -*- mode: ruby -*-
VAGRANTFILE_API_VERSION = "2"

$provision_script = <<PROVISION
    apt-get -y update
    apt-get install ifupdown -y
    apt-get install nodejs mongodb mongodb-clients mongodb-server npm -y
PROVISION

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    virtualbox_vm_name = "node-dev"

    config.vm.provision "shell", inline: $provision_script
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", id: "shared-root", owner: "vagrant", group: "vagrant", mount_options: ["ttl=1,dmode=775,fmode=775"]

    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--name", virtualbox_vm_name]
        vb.customize ["modifyvm", :id, "--memory", "2048"] 
    end

    config.vm.define virtualbox_vm_name do |app|
        app.vm.hostname = "node-dev"
        app.vm.box = "bento/ubuntu-18.04"
        app.vm.network "private_network", ip: "192.168.33.11"
    end
end
